<option value="adrar" selected>أدرار</option>
<option value="chlef">الشلف</option>
<option value="aghouat">الأغواط</option>
<option value="oum bouaghi">أم البواقي</option>
<option value="batna">باتنة</option>
<option value="bejaia">بجاية</option>
<option value="biskra">بسكرة</option>
<option value="bechar">بشار</option>
<option value="blida">البليدة</option>
<option value="bouira">البويرة</option>
<option value="tebessa">تبسة</option>
<option value="tlemcen">تلمسان</option>
<option value="tiaret">تيارت</option>
<option value="tizi ouzou">تيزي وزو</option>
<option value="alger">الجزائر العاصمة</option>
<option value="djelfa">الجلفة</option>
<option value="jijel">جيجل</option>
<option value="setif">سطيف</option>
<option value="saida">سعيدة</option>
<option value="skikda">سكيكدة</option>
<option value="sidi bellabas">سيدي بلعباس</option>
<option value="annaba">عنابة</option>
<option value="guelma">قالمة</option>
<option value="constantine">قسنطينة</option>
<option value="medea">المدية</option>
<option value="mostaganem">مستغانم</option>
<option value="m'sila">المسيلة</option>
<option value="mascara">معسكر</option>
<option value="ouergla">ورقلة</option>
<option value="oran">وهران</option>
<option value="bayadh">البيض</option>
<option value="bordj bou arreridj">برج بوعريريج</option>
<option value="boumerdes">بومرداس</option>
<option value="taraf">الطارف</option>
<option value="tissimsilt">تيسمسيلت</option>
<option value="elouadi">الوادي</option>
<option value="khenchla">خنشلة</option>
<option value="souk ahras">سوق أهراس</option>
<option value="tipza">تيبازة</option>
<option value="mila">ميلة</option>
<option value="ain deffla">عين الدفلى</option>
<option value="naama">النعامة</option>
<option value="ein timouchent">عين تموشنت</option>
<option value="gherdaia">غرداية</option>
<option value="guelizene">غليزان</option>